### ISSUE TITLE
Integration messes up state history graphs

### ISSUE THREAD

**Issue by YannickvanVugt** [aex351/home-assistant-neerslag-card#19] opened 2021-06-08 11:00 UTC
Since I installed this card I have issues with state history graphs, the states will go black or blank and no text will be readable. When deleting the integration it is back to normal.

Issue only seems to occur at first loading of a graph, after a refresh of the page it is all ok, until close the tab/app and open it again.

Core: core-2021.6.3
Supervisor: supervisor-2021.05.4
Hass OS: Home Assistant OS 5.13
HACS integration: 1.12.4
HACS frontend: 20210429001005

**Without Neerslag card installed**
![image](https://user-images.githubusercontent.com/31463746/121173998-bdfc3880-c859-11eb-9d4f-16052948f98b.png)

**With Neerslag card installed**
![image](https://user-images.githubusercontent.com/31463746/121173557-3b737900-c859-11eb-8bd6-20b6c9880691.png)

**Comment by aex351** [comment] 2021-06-08 22:55
I am unable to reproduce this. The `Neerslag Card` is a web component, which means from a technical point of view that it's a single package that does not impact other packages. There is no specific code that is changing anything from the state history graphs. I'm assuming the problem is caused by some form of caching/loading mechanism of Home Assistant itself. I am not sure how the `Neerslag Card` could be the root cause of this problem.

**Comment by YannickvanVugt** [comment] 2021-06-09 16:28
> I am unable to reproduce this. The `Neerslag Card` is a web component, which means from a technical point of view that it's a single package that does not impact other packages. There is no specific code that is changing anything from the state history graphs. I'm assuming the problem is caused by some form of caching/loading mechanism of Home Assistant itself. I am not sure how the `Neerslag Card` could be the root cause of this problem.

Isn't it strange that it is both happening in the app as well as the web version, both in Chrome and Firefox, all latest version?
Install is fresh, re-did everything last weekend.

**Comment by aex351** [comment] 2021-06-09 17:30
It is indeed strange, however I am not convinced that the `Neerslag Card` could be the cause of this. The only connection is that it seems to happen in your case after you installed the `Neerslag Card`. Maybe you can check if there are any log files in Home Assistant that might point to the root cause and check in the browser developer console to see if there are errors/indicators.

Looking at your screenshot it seems to me that the particular component (history graph) isn't loading correctly.

**Comment by aex351** [comment] 2021-06-26 23:45
Closing this issue as there are no other reports / comments on it.

**Closed by aex351** 2021-06-26 23:45 UTC
